// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class ExportCsvDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.ExportCsvDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public ExportCsvDocument(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.ExportCsvDocument"));
	}

	protected ExportCsvDocument(IContext context, IMendixObject exportCsvDocumentMendixObject)
	{
		super(context, exportCsvDocumentMendixObject);
		if (!Core.isSubClassOf("MyFirstModule.ExportCsvDocument", exportCsvDocumentMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.ExportCsvDocument");
	}

	/**
	 * @deprecated Use 'new ExportCsvDocument(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ExportCsvDocument create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.ExportCsvDocument");
		return new myfirstmodule.proxies.ExportCsvDocument(context, mendixObject);
	}

	/**
	 * @deprecated Use 'ExportCsvDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ExportCsvDocument initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.ExportCsvDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ExportCsvDocument initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ExportCsvDocument(context, mendixObject);
	}

	public static myfirstmodule.proxies.ExportCsvDocument load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ExportCsvDocument.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.ExportCsvDocument> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.ExportCsvDocument> result = new java.util.ArrayList<myfirstmodule.proxies.ExportCsvDocument>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.ExportCsvDocument" + xpathConstraint))
			result.add(myfirstmodule.proxies.ExportCsvDocument.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ExportCsvDocument that = (myfirstmodule.proxies.ExportCsvDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.ExportCsvDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
