// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class ExportCsv
{
	private final IMendixObject exportCsvMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.ExportCsv";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CsvData("CsvData");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public ExportCsv(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.ExportCsv"));
	}

	protected ExportCsv(IContext context, IMendixObject exportCsvMendixObject)
	{
		if (exportCsvMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.ExportCsv", exportCsvMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.ExportCsv");

		this.exportCsvMendixObject = exportCsvMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new ExportCsv(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ExportCsv create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.ExportCsv");
		return new myfirstmodule.proxies.ExportCsv(context, mendixObject);
	}

	/**
	 * @deprecated Use 'ExportCsv.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ExportCsv initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.ExportCsv.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ExportCsv initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ExportCsv(context, mendixObject);
	}

	public static myfirstmodule.proxies.ExportCsv load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ExportCsv.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CsvData
	 */
	public final String getCsvData()
	{
		return getCsvData(getContext());
	}

	/**
	 * @param context
	 * @return value of CsvData
	 */
	public final String getCsvData(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CsvData.toString());
	}

	/**
	 * Set value of CsvData
	 * @param csvdata
	 */
	public final void setCsvData(String csvdata)
	{
		setCsvData(getContext(), csvdata);
	}

	/**
	 * Set value of CsvData
	 * @param context
	 * @param csvdata
	 */
	public final void setCsvData(IContext context, String csvdata)
	{
		getMendixObject().setValue(context, MemberNames.CsvData.toString(), csvdata);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return exportCsvMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ExportCsv that = (myfirstmodule.proxies.ExportCsv) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.ExportCsv";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
