// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Incident
{
	private final IMendixObject incidentMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Incident";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		incidentDate("incidentDate"),
		incidentTitle("incidentTitle"),
		incidentDescription("incidentDescription"),
		Incident_Category("MyFirstModule.Incident_Category"),
		Incident_Carrier("MyFirstModule.Incident_Carrier"),
		Incident_Employee("MyFirstModule.Incident_Employee");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Incident(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Incident"));
	}

	protected Incident(IContext context, IMendixObject incidentMendixObject)
	{
		if (incidentMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Incident", incidentMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Incident");

		this.incidentMendixObject = incidentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Incident.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Incident initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Incident.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Incident initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Incident(context, mendixObject);
	}

	public static myfirstmodule.proxies.Incident load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Incident.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Incident> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Incident> result = new java.util.ArrayList<myfirstmodule.proxies.Incident>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Incident" + xpathConstraint))
			result.add(myfirstmodule.proxies.Incident.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of incidentDate
	 */
	public final java.util.Date getincidentDate()
	{
		return getincidentDate(getContext());
	}

	/**
	 * @param context
	 * @return value of incidentDate
	 */
	public final java.util.Date getincidentDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.incidentDate.toString());
	}

	/**
	 * Set value of incidentDate
	 * @param incidentdate
	 */
	public final void setincidentDate(java.util.Date incidentdate)
	{
		setincidentDate(getContext(), incidentdate);
	}

	/**
	 * Set value of incidentDate
	 * @param context
	 * @param incidentdate
	 */
	public final void setincidentDate(IContext context, java.util.Date incidentdate)
	{
		getMendixObject().setValue(context, MemberNames.incidentDate.toString(), incidentdate);
	}

	/**
	 * @return value of incidentTitle
	 */
	public final String getincidentTitle()
	{
		return getincidentTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of incidentTitle
	 */
	public final String getincidentTitle(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.incidentTitle.toString());
	}

	/**
	 * Set value of incidentTitle
	 * @param incidenttitle
	 */
	public final void setincidentTitle(String incidenttitle)
	{
		setincidentTitle(getContext(), incidenttitle);
	}

	/**
	 * Set value of incidentTitle
	 * @param context
	 * @param incidenttitle
	 */
	public final void setincidentTitle(IContext context, String incidenttitle)
	{
		getMendixObject().setValue(context, MemberNames.incidentTitle.toString(), incidenttitle);
	}

	/**
	 * @return value of incidentDescription
	 */
	public final String getincidentDescription()
	{
		return getincidentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of incidentDescription
	 */
	public final String getincidentDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.incidentDescription.toString());
	}

	/**
	 * Set value of incidentDescription
	 * @param incidentdescription
	 */
	public final void setincidentDescription(String incidentdescription)
	{
		setincidentDescription(getContext(), incidentdescription);
	}

	/**
	 * Set value of incidentDescription
	 * @param context
	 * @param incidentdescription
	 */
	public final void setincidentDescription(IContext context, String incidentdescription)
	{
		getMendixObject().setValue(context, MemberNames.incidentDescription.toString(), incidentdescription);
	}

	/**
	 * @return value of Incident_Category
	 */
	public final myfirstmodule.proxies.Category getIncident_Category() throws CoreException
	{
		return getIncident_Category(getContext());
	}

	/**
	 * @param context
	 * @return value of Incident_Category
	 */
	public final myfirstmodule.proxies.Category getIncident_Category(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Category result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Incident_Category.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Incident_Category
	 * @param incident_category
	 */
	public final void setIncident_Category(myfirstmodule.proxies.Category incident_category)
	{
		setIncident_Category(getContext(), incident_category);
	}

	/**
	 * Set value of Incident_Category
	 * @param context
	 * @param incident_category
	 */
	public final void setIncident_Category(IContext context, myfirstmodule.proxies.Category incident_category)
	{
		if (incident_category == null)
			getMendixObject().setValue(context, MemberNames.Incident_Category.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Incident_Category.toString(), incident_category.getMendixObject().getId());
	}

	/**
	 * @return value of Incident_Carrier
	 */
	public final myfirstmodule.proxies.Carrier getIncident_Carrier() throws CoreException
	{
		return getIncident_Carrier(getContext());
	}

	/**
	 * @param context
	 * @return value of Incident_Carrier
	 */
	public final myfirstmodule.proxies.Carrier getIncident_Carrier(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Carrier result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Incident_Carrier.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Carrier.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Incident_Carrier
	 * @param incident_carrier
	 */
	public final void setIncident_Carrier(myfirstmodule.proxies.Carrier incident_carrier)
	{
		setIncident_Carrier(getContext(), incident_carrier);
	}

	/**
	 * Set value of Incident_Carrier
	 * @param context
	 * @param incident_carrier
	 */
	public final void setIncident_Carrier(IContext context, myfirstmodule.proxies.Carrier incident_carrier)
	{
		if (incident_carrier == null)
			getMendixObject().setValue(context, MemberNames.Incident_Carrier.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Incident_Carrier.toString(), incident_carrier.getMendixObject().getId());
	}

	/**
	 * @return value of Incident_Employee
	 */
	public final myfirstmodule.proxies.Employee getIncident_Employee() throws CoreException
	{
		return getIncident_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Incident_Employee
	 */
	public final myfirstmodule.proxies.Employee getIncident_Employee(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Employee result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Incident_Employee.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Incident_Employee
	 * @param incident_employee
	 */
	public final void setIncident_Employee(myfirstmodule.proxies.Employee incident_employee)
	{
		setIncident_Employee(getContext(), incident_employee);
	}

	/**
	 * Set value of Incident_Employee
	 * @param context
	 * @param incident_employee
	 */
	public final void setIncident_Employee(IContext context, myfirstmodule.proxies.Employee incident_employee)
	{
		if (incident_employee == null)
			getMendixObject().setValue(context, MemberNames.Incident_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Incident_Employee.toString(), incident_employee.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return incidentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Incident that = (myfirstmodule.proxies.Incident) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Incident";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
