// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TransientSalesOrderPivotTable
{
	private final IMendixObject transientSalesOrderPivotTableMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.TransientSalesOrderPivotTable";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		orderNumber("orderNumber"),
		orderDate("orderDate"),
		period("period"),
		totalSalesValue("totalSalesValue"),
		itemCount("itemCount"),
		region("region"),
		employeeNumber("employeeNumber"),
		employeeName("employeeName"),
		totalSalesValueCcy("totalSalesValueCcy"),
		TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters("MyFirstModule.TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TransientSalesOrderPivotTable(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.TransientSalesOrderPivotTable"));
	}

	protected TransientSalesOrderPivotTable(IContext context, IMendixObject transientSalesOrderPivotTableMendixObject)
	{
		if (transientSalesOrderPivotTableMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.TransientSalesOrderPivotTable", transientSalesOrderPivotTableMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.TransientSalesOrderPivotTable");

		this.transientSalesOrderPivotTableMendixObject = transientSalesOrderPivotTableMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransientSalesOrderPivotTable.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TransientSalesOrderPivotTable initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.TransientSalesOrderPivotTable.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TransientSalesOrderPivotTable initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TransientSalesOrderPivotTable(context, mendixObject);
	}

	public static myfirstmodule.proxies.TransientSalesOrderPivotTable load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TransientSalesOrderPivotTable.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of orderNumber
	 */
	public final Long getorderNumber()
	{
		return getorderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of orderNumber
	 */
	public final Long getorderNumber(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.orderNumber.toString());
	}

	/**
	 * Set value of orderNumber
	 * @param ordernumber
	 */
	public final void setorderNumber(Long ordernumber)
	{
		setorderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of orderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setorderNumber(IContext context, Long ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.orderNumber.toString(), ordernumber);
	}

	/**
	 * @return value of orderDate
	 */
	public final java.util.Date getorderDate()
	{
		return getorderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of orderDate
	 */
	public final java.util.Date getorderDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.orderDate.toString());
	}

	/**
	 * Set value of orderDate
	 * @param orderdate
	 */
	public final void setorderDate(java.util.Date orderdate)
	{
		setorderDate(getContext(), orderdate);
	}

	/**
	 * Set value of orderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setorderDate(IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.orderDate.toString(), orderdate);
	}

	/**
	 * @return value of period
	 */
	public final String getperiod()
	{
		return getperiod(getContext());
	}

	/**
	 * @param context
	 * @return value of period
	 */
	public final String getperiod(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.period.toString());
	}

	/**
	 * Set value of period
	 * @param period
	 */
	public final void setperiod(String period)
	{
		setperiod(getContext(), period);
	}

	/**
	 * Set value of period
	 * @param context
	 * @param period
	 */
	public final void setperiod(IContext context, String period)
	{
		getMendixObject().setValue(context, MemberNames.period.toString(), period);
	}

	/**
	 * @return value of totalSalesValue
	 */
	public final java.math.BigDecimal gettotalSalesValue()
	{
		return gettotalSalesValue(getContext());
	}

	/**
	 * @param context
	 * @return value of totalSalesValue
	 */
	public final java.math.BigDecimal gettotalSalesValue(IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.totalSalesValue.toString());
	}

	/**
	 * Set value of totalSalesValue
	 * @param totalsalesvalue
	 */
	public final void settotalSalesValue(java.math.BigDecimal totalsalesvalue)
	{
		settotalSalesValue(getContext(), totalsalesvalue);
	}

	/**
	 * Set value of totalSalesValue
	 * @param context
	 * @param totalsalesvalue
	 */
	public final void settotalSalesValue(IContext context, java.math.BigDecimal totalsalesvalue)
	{
		getMendixObject().setValue(context, MemberNames.totalSalesValue.toString(), totalsalesvalue);
	}

	/**
	 * @return value of itemCount
	 */
	public final Integer getitemCount()
	{
		return getitemCount(getContext());
	}

	/**
	 * @param context
	 * @return value of itemCount
	 */
	public final Integer getitemCount(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.itemCount.toString());
	}

	/**
	 * Set value of itemCount
	 * @param itemcount
	 */
	public final void setitemCount(Integer itemcount)
	{
		setitemCount(getContext(), itemcount);
	}

	/**
	 * Set value of itemCount
	 * @param context
	 * @param itemcount
	 */
	public final void setitemCount(IContext context, Integer itemcount)
	{
		getMendixObject().setValue(context, MemberNames.itemCount.toString(), itemcount);
	}

	/**
	 * Set value of region
	 * @param region
	 */
	public final myfirstmodule.proxies.Region getregion()
	{
		return getregion(getContext());
	}

	/**
	 * @param context
	 * @return value of region
	 */
	public final myfirstmodule.proxies.Region getregion(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.region.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Region.valueOf((String) obj);
	}

	/**
	 * Set value of region
	 * @param region
	 */
	public final void setregion(myfirstmodule.proxies.Region region)
	{
		setregion(getContext(), region);
	}

	/**
	 * Set value of region
	 * @param context
	 * @param region
	 */
	public final void setregion(IContext context, myfirstmodule.proxies.Region region)
	{
		if (region != null)
			getMendixObject().setValue(context, MemberNames.region.toString(), region.toString());
		else
			getMendixObject().setValue(context, MemberNames.region.toString(), null);
	}

	/**
	 * @return value of employeeNumber
	 */
	public final Long getemployeeNumber()
	{
		return getemployeeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of employeeNumber
	 */
	public final Long getemployeeNumber(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.employeeNumber.toString());
	}

	/**
	 * Set value of employeeNumber
	 * @param employeenumber
	 */
	public final void setemployeeNumber(Long employeenumber)
	{
		setemployeeNumber(getContext(), employeenumber);
	}

	/**
	 * Set value of employeeNumber
	 * @param context
	 * @param employeenumber
	 */
	public final void setemployeeNumber(IContext context, Long employeenumber)
	{
		getMendixObject().setValue(context, MemberNames.employeeNumber.toString(), employeenumber);
	}

	/**
	 * @return value of employeeName
	 */
	public final String getemployeeName()
	{
		return getemployeeName(getContext());
	}

	/**
	 * @param context
	 * @return value of employeeName
	 */
	public final String getemployeeName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.employeeName.toString());
	}

	/**
	 * Set value of employeeName
	 * @param employeename
	 */
	public final void setemployeeName(String employeename)
	{
		setemployeeName(getContext(), employeename);
	}

	/**
	 * Set value of employeeName
	 * @param context
	 * @param employeename
	 */
	public final void setemployeeName(IContext context, String employeename)
	{
		getMendixObject().setValue(context, MemberNames.employeeName.toString(), employeename);
	}

	/**
	 * @return value of totalSalesValueCcy
	 */
	public final Double gettotalSalesValueCcy()
	{
		return gettotalSalesValueCcy(getContext());
	}

	/**
	 * @param context
	 * @return value of totalSalesValueCcy
	 */
	public final Double gettotalSalesValueCcy(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.totalSalesValueCcy.toString());
	}

	/**
	 * Set value of totalSalesValueCcy
	 * @param totalsalesvalueccy
	 */
	public final void settotalSalesValueCcy(Double totalsalesvalueccy)
	{
		settotalSalesValueCcy(getContext(), totalsalesvalueccy);
	}

	/**
	 * Set value of totalSalesValueCcy
	 * @param context
	 * @param totalsalesvalueccy
	 */
	public final void settotalSalesValueCcy(IContext context, Double totalsalesvalueccy)
	{
		getMendixObject().setValue(context, MemberNames.totalSalesValueCcy.toString(), totalsalesvalueccy);
	}

	/**
	 * @return value of TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters
	 */
	public final myfirstmodule.proxies.TransientSalesOrderPivotTableParameters getTransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters() throws CoreException
	{
		return getTransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters
	 */
	public final myfirstmodule.proxies.TransientSalesOrderPivotTableParameters getTransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters(IContext context) throws CoreException
	{
		myfirstmodule.proxies.TransientSalesOrderPivotTableParameters result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.TransientSalesOrderPivotTableParameters.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters
	 * @param transientsalesorderpivottable_transientsalesorderpivottableparameters
	 */
	public final void setTransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters(myfirstmodule.proxies.TransientSalesOrderPivotTableParameters transientsalesorderpivottable_transientsalesorderpivottableparameters)
	{
		setTransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters(getContext(), transientsalesorderpivottable_transientsalesorderpivottableparameters);
	}

	/**
	 * Set value of TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters
	 * @param context
	 * @param transientsalesorderpivottable_transientsalesorderpivottableparameters
	 */
	public final void setTransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters(IContext context, myfirstmodule.proxies.TransientSalesOrderPivotTableParameters transientsalesorderpivottable_transientsalesorderpivottableparameters)
	{
		if (transientsalesorderpivottable_transientsalesorderpivottableparameters == null)
			getMendixObject().setValue(context, MemberNames.TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TransientSalesOrderPivotTable_TransientSalesOrderPivotTableParameters.toString(), transientsalesorderpivottable_transientsalesorderpivottableparameters.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return transientSalesOrderPivotTableMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TransientSalesOrderPivotTable that = (myfirstmodule.proxies.TransientSalesOrderPivotTable) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.TransientSalesOrderPivotTable";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
