// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TransientIncidentPivotTableCellRow
{
	private final IMendixObject transientIncidentPivotTableCellRowMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.TransientIncidentPivotTableCellRow";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		incidentDate("incidentDate"),
		incidentTitle("incidentTitle"),
		incidentDescription("incidentDescription"),
		employeeNumber("employeeNumber"),
		employeeName("employeeName"),
		TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell("MyFirstModule.TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TransientIncidentPivotTableCellRow(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.TransientIncidentPivotTableCellRow"));
	}

	protected TransientIncidentPivotTableCellRow(IContext context, IMendixObject transientIncidentPivotTableCellRowMendixObject)
	{
		if (transientIncidentPivotTableCellRowMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.TransientIncidentPivotTableCellRow", transientIncidentPivotTableCellRowMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.TransientIncidentPivotTableCellRow");

		this.transientIncidentPivotTableCellRowMendixObject = transientIncidentPivotTableCellRowMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransientIncidentPivotTableCellRow.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TransientIncidentPivotTableCellRow initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.TransientIncidentPivotTableCellRow.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TransientIncidentPivotTableCellRow initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TransientIncidentPivotTableCellRow(context, mendixObject);
	}

	public static myfirstmodule.proxies.TransientIncidentPivotTableCellRow load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TransientIncidentPivotTableCellRow.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of incidentDate
	 */
	public final java.util.Date getincidentDate()
	{
		return getincidentDate(getContext());
	}

	/**
	 * @param context
	 * @return value of incidentDate
	 */
	public final java.util.Date getincidentDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.incidentDate.toString());
	}

	/**
	 * Set value of incidentDate
	 * @param incidentdate
	 */
	public final void setincidentDate(java.util.Date incidentdate)
	{
		setincidentDate(getContext(), incidentdate);
	}

	/**
	 * Set value of incidentDate
	 * @param context
	 * @param incidentdate
	 */
	public final void setincidentDate(IContext context, java.util.Date incidentdate)
	{
		getMendixObject().setValue(context, MemberNames.incidentDate.toString(), incidentdate);
	}

	/**
	 * @return value of incidentTitle
	 */
	public final String getincidentTitle()
	{
		return getincidentTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of incidentTitle
	 */
	public final String getincidentTitle(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.incidentTitle.toString());
	}

	/**
	 * Set value of incidentTitle
	 * @param incidenttitle
	 */
	public final void setincidentTitle(String incidenttitle)
	{
		setincidentTitle(getContext(), incidenttitle);
	}

	/**
	 * Set value of incidentTitle
	 * @param context
	 * @param incidenttitle
	 */
	public final void setincidentTitle(IContext context, String incidenttitle)
	{
		getMendixObject().setValue(context, MemberNames.incidentTitle.toString(), incidenttitle);
	}

	/**
	 * @return value of incidentDescription
	 */
	public final String getincidentDescription()
	{
		return getincidentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of incidentDescription
	 */
	public final String getincidentDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.incidentDescription.toString());
	}

	/**
	 * Set value of incidentDescription
	 * @param incidentdescription
	 */
	public final void setincidentDescription(String incidentdescription)
	{
		setincidentDescription(getContext(), incidentdescription);
	}

	/**
	 * Set value of incidentDescription
	 * @param context
	 * @param incidentdescription
	 */
	public final void setincidentDescription(IContext context, String incidentdescription)
	{
		getMendixObject().setValue(context, MemberNames.incidentDescription.toString(), incidentdescription);
	}

	/**
	 * @return value of employeeNumber
	 */
	public final Long getemployeeNumber()
	{
		return getemployeeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of employeeNumber
	 */
	public final Long getemployeeNumber(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.employeeNumber.toString());
	}

	/**
	 * Set value of employeeNumber
	 * @param employeenumber
	 */
	public final void setemployeeNumber(Long employeenumber)
	{
		setemployeeNumber(getContext(), employeenumber);
	}

	/**
	 * Set value of employeeNumber
	 * @param context
	 * @param employeenumber
	 */
	public final void setemployeeNumber(IContext context, Long employeenumber)
	{
		getMendixObject().setValue(context, MemberNames.employeeNumber.toString(), employeenumber);
	}

	/**
	 * @return value of employeeName
	 */
	public final String getemployeeName()
	{
		return getemployeeName(getContext());
	}

	/**
	 * @param context
	 * @return value of employeeName
	 */
	public final String getemployeeName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.employeeName.toString());
	}

	/**
	 * Set value of employeeName
	 * @param employeename
	 */
	public final void setemployeeName(String employeename)
	{
		setemployeeName(getContext(), employeename);
	}

	/**
	 * Set value of employeeName
	 * @param context
	 * @param employeename
	 */
	public final void setemployeeName(IContext context, String employeename)
	{
		getMendixObject().setValue(context, MemberNames.employeeName.toString(), employeename);
	}

	/**
	 * @return value of TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell
	 */
	public final myfirstmodule.proxies.TransientIncidentPivotTableCell getTransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell() throws CoreException
	{
		return getTransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell(getContext());
	}

	/**
	 * @param context
	 * @return value of TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell
	 */
	public final myfirstmodule.proxies.TransientIncidentPivotTableCell getTransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell(IContext context) throws CoreException
	{
		myfirstmodule.proxies.TransientIncidentPivotTableCell result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.TransientIncidentPivotTableCell.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell
	 * @param transientincidentpivottablecellrow_transientincidentpivottablecell
	 */
	public final void setTransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell(myfirstmodule.proxies.TransientIncidentPivotTableCell transientincidentpivottablecellrow_transientincidentpivottablecell)
	{
		setTransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell(getContext(), transientincidentpivottablecellrow_transientincidentpivottablecell);
	}

	/**
	 * Set value of TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell
	 * @param context
	 * @param transientincidentpivottablecellrow_transientincidentpivottablecell
	 */
	public final void setTransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell(IContext context, myfirstmodule.proxies.TransientIncidentPivotTableCell transientincidentpivottablecellrow_transientincidentpivottablecell)
	{
		if (transientincidentpivottablecellrow_transientincidentpivottablecell == null)
			getMendixObject().setValue(context, MemberNames.TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TransientIncidentPivotTableCellRow_TransientIncidentPivotTableCell.toString(), transientincidentpivottablecellrow_transientincidentpivottablecell.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return transientIncidentPivotTableCellRowMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TransientIncidentPivotTableCellRow that = (myfirstmodule.proxies.TransientIncidentPivotTableCellRow) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.TransientIncidentPivotTableCellRow";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
