// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TransientRelationPivotTable
{
	private final IMendixObject transientRelationPivotTableMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.TransientRelationPivotTable";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		Region("Region"),
		employeeNumber("employeeNumber"),
		employeeName("employeeName"),
		carrierNumber("carrierNumber"),
		carrierName("carrierName"),
		TransientRelationPivotTable_TransientRelationPivotTableParameters("MyFirstModule.TransientRelationPivotTable_TransientRelationPivotTableParameters");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TransientRelationPivotTable(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.TransientRelationPivotTable"));
	}

	protected TransientRelationPivotTable(IContext context, IMendixObject transientRelationPivotTableMendixObject)
	{
		if (transientRelationPivotTableMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.TransientRelationPivotTable", transientRelationPivotTableMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.TransientRelationPivotTable");

		this.transientRelationPivotTableMendixObject = transientRelationPivotTableMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransientRelationPivotTable.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TransientRelationPivotTable initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.TransientRelationPivotTable.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TransientRelationPivotTable initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TransientRelationPivotTable(context, mendixObject);
	}

	public static myfirstmodule.proxies.TransientRelationPivotTable load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TransientRelationPivotTable.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Description
	 */
	public final String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final String getDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(IContext context, String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final myfirstmodule.proxies.Region getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final myfirstmodule.proxies.Region getRegion(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Region.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Region.valueOf((String) obj);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(myfirstmodule.proxies.Region region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(IContext context, myfirstmodule.proxies.Region region)
	{
		if (region != null)
			getMendixObject().setValue(context, MemberNames.Region.toString(), region.toString());
		else
			getMendixObject().setValue(context, MemberNames.Region.toString(), null);
	}

	/**
	 * @return value of employeeNumber
	 */
	public final Long getemployeeNumber()
	{
		return getemployeeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of employeeNumber
	 */
	public final Long getemployeeNumber(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.employeeNumber.toString());
	}

	/**
	 * Set value of employeeNumber
	 * @param employeenumber
	 */
	public final void setemployeeNumber(Long employeenumber)
	{
		setemployeeNumber(getContext(), employeenumber);
	}

	/**
	 * Set value of employeeNumber
	 * @param context
	 * @param employeenumber
	 */
	public final void setemployeeNumber(IContext context, Long employeenumber)
	{
		getMendixObject().setValue(context, MemberNames.employeeNumber.toString(), employeenumber);
	}

	/**
	 * @return value of employeeName
	 */
	public final String getemployeeName()
	{
		return getemployeeName(getContext());
	}

	/**
	 * @param context
	 * @return value of employeeName
	 */
	public final String getemployeeName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.employeeName.toString());
	}

	/**
	 * Set value of employeeName
	 * @param employeename
	 */
	public final void setemployeeName(String employeename)
	{
		setemployeeName(getContext(), employeename);
	}

	/**
	 * Set value of employeeName
	 * @param context
	 * @param employeename
	 */
	public final void setemployeeName(IContext context, String employeename)
	{
		getMendixObject().setValue(context, MemberNames.employeeName.toString(), employeename);
	}

	/**
	 * @return value of carrierNumber
	 */
	public final Long getcarrierNumber()
	{
		return getcarrierNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of carrierNumber
	 */
	public final Long getcarrierNumber(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.carrierNumber.toString());
	}

	/**
	 * Set value of carrierNumber
	 * @param carriernumber
	 */
	public final void setcarrierNumber(Long carriernumber)
	{
		setcarrierNumber(getContext(), carriernumber);
	}

	/**
	 * Set value of carrierNumber
	 * @param context
	 * @param carriernumber
	 */
	public final void setcarrierNumber(IContext context, Long carriernumber)
	{
		getMendixObject().setValue(context, MemberNames.carrierNumber.toString(), carriernumber);
	}

	/**
	 * @return value of carrierName
	 */
	public final String getcarrierName()
	{
		return getcarrierName(getContext());
	}

	/**
	 * @param context
	 * @return value of carrierName
	 */
	public final String getcarrierName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.carrierName.toString());
	}

	/**
	 * Set value of carrierName
	 * @param carriername
	 */
	public final void setcarrierName(String carriername)
	{
		setcarrierName(getContext(), carriername);
	}

	/**
	 * Set value of carrierName
	 * @param context
	 * @param carriername
	 */
	public final void setcarrierName(IContext context, String carriername)
	{
		getMendixObject().setValue(context, MemberNames.carrierName.toString(), carriername);
	}

	/**
	 * @return value of TransientRelationPivotTable_TransientRelationPivotTableParameters
	 */
	public final myfirstmodule.proxies.TransientRelationPivotTableParameters getTransientRelationPivotTable_TransientRelationPivotTableParameters() throws CoreException
	{
		return getTransientRelationPivotTable_TransientRelationPivotTableParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of TransientRelationPivotTable_TransientRelationPivotTableParameters
	 */
	public final myfirstmodule.proxies.TransientRelationPivotTableParameters getTransientRelationPivotTable_TransientRelationPivotTableParameters(IContext context) throws CoreException
	{
		myfirstmodule.proxies.TransientRelationPivotTableParameters result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransientRelationPivotTable_TransientRelationPivotTableParameters.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.TransientRelationPivotTableParameters.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TransientRelationPivotTable_TransientRelationPivotTableParameters
	 * @param transientrelationpivottable_transientrelationpivottableparameters
	 */
	public final void setTransientRelationPivotTable_TransientRelationPivotTableParameters(myfirstmodule.proxies.TransientRelationPivotTableParameters transientrelationpivottable_transientrelationpivottableparameters)
	{
		setTransientRelationPivotTable_TransientRelationPivotTableParameters(getContext(), transientrelationpivottable_transientrelationpivottableparameters);
	}

	/**
	 * Set value of TransientRelationPivotTable_TransientRelationPivotTableParameters
	 * @param context
	 * @param transientrelationpivottable_transientrelationpivottableparameters
	 */
	public final void setTransientRelationPivotTable_TransientRelationPivotTableParameters(IContext context, myfirstmodule.proxies.TransientRelationPivotTableParameters transientrelationpivottable_transientrelationpivottableparameters)
	{
		if (transientrelationpivottable_transientrelationpivottableparameters == null)
			getMendixObject().setValue(context, MemberNames.TransientRelationPivotTable_TransientRelationPivotTableParameters.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TransientRelationPivotTable_TransientRelationPivotTableParameters.toString(), transientrelationpivottable_transientrelationpivottableparameters.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return transientRelationPivotTableMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TransientRelationPivotTable that = (myfirstmodule.proxies.TransientRelationPivotTable) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.TransientRelationPivotTable";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
